# 只需要 Gateway + 基本的 VirtualService
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: basic-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-vs
spec:
  hosts:
  - "*"
  gateways:
  - basic-gateway
  http:
  - route:
    - destination:
        host: api-service.act-test.svc.cluster.local
        port:
          number: 80