apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser-deployment
  namespace: act-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parser
  template:
    metadata:
      labels:
        app: parser
    spec:
      containers:
      - name: parser
        image: gpu-harbor.act.buaa.edu.cn/user-wangxi25/minio-parser:latest # <-- IMPORTANT: Replace with your image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
        env:
        - name: HF_ENDPOINT
          value: "https://hf-mirror.com"
        - name: MINIO_ENDPOINT
          value: "minio-service:9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: MINIO_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: parser-service
  namespace: act-test
spec:
  selector:
    app: parser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort 