apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reranker-model-cache-pvc
  namespace: act-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi # Adjust size based on your model cache needs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reranker-deployment
  namespace: act-test
  labels:
    app: reranker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reranker-service
  template:
    metadata:
      labels:
        app: reranker-service
    spec:
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: reranker-model-cache-pvc
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: reranker-container
        image: ghcr.nju.edu.cn/sasha0552/vllm:latest
        args: [
          "--model", "BAAI/bge-reranker-base",
          "--trust-remote-code",
          "--port", "8000"
        ]
        env:
        - name: HF_ENDPOINT
          value: "https://hf-mirror.com"
        ports:
        - containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: "1"
          requests:
            nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: cache-volume
        - mountPath: /dev/shm
          name: dshm
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8000
        #   initialDelaySeconds: 60
        #   periodSeconds: 15
        #   timeoutSeconds: 5
        #   failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: reranker-service
  namespace: act-test
spec:
  selector:
    app: reranker-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  type: NodePort 