apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulate-deployment
  namespace: act-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulate
  template:
    metadata:
      labels:
        app: simulate
    spec:
      containers:
      - name: simulate
        image: gpu-harbor.act.buaa.edu.cn/user-wangxi25/simulate:1104v1
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
        env:
        - name: HF_ENDPOINT
          value: "https://hf-mirror.com"
        
---
apiVersion: v1
kind: Service
metadata:
  name: simulate-service
  namespace: act-test
spec:
  selector:
    app: simulate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort 